### PR TITLE
Feature: Update endpoints to using service specific UUIDs.

### PR DESCRIPTION
**Pull request by isaschm**
Update existing models and endpoints to the use of service-specific UUIDs.

### CODE REVIEW

**Comment by isaschm** [comment]
I think the failing Security Check is not my fault??

**Review by akkbng — APPROVED** [review]
I'm bit out of loop with the current implementation of the Account keys, but functionality wise all look okay to me. Thanks @isaschm  😊

**Comment by akkbng** [comment]
@isaschm  one question from my side: how is PR fixing the issue #33 ? Or do we get the generated account keys from some other service?

**Comment by isaschm** [comment]
> @isaschm one question from my side: how is this PR fixing the issue #33 ? Or do we get the generated account keys from some other service?

We get a generated account key from the koda service :)

**Comment by isaschm** [comment]
I ran the tests again and the service starts 🤷‍♀️

**Pull request merged**
